### PR TITLE
Drop deprecated parameters from vectorize.table()

### LINKED ISSUE #146: drop deprecated parameters from `vectorize.table()`
`search_alg` is deprecated, in favor of [index_dist_type](https://github.com/tembo-io/pg_vectorize/blob/9e013e3c9c5702c982ca74415ff396074a744cb7/extension/src/api.rs#L22). Drop search_alg from the parameter and downstream call tree.

### PR DESCRIPTION
**Pull request by Neptune650**
/fixes #146
/claim #146

I've done some changes to make sure it builds, @ChuckHend please review.

### CODE REVIEW

**Comment by Bhavyajain21** [comment]
@Neptune650 , are the builds passing here?

**Comment by Neptune650** [comment]
> @Neptune650 , are the builds passing here?

@Bhavyajain21 Yes

**Comment by Bhavyajain21** [comment]
Did you do `make run`?

**Comment by Neptune650** [comment]
> Did you do `make run`?

@Bhavyajain21 yes

**Pull request closed without merging**
