### PR TITLE
feat(docs): Add documentation on `where` clause and partial indices

### LINKED ISSUE #143: documentation and examples for filtering
`vectorize.search()` supports some limited filtering (the filtering happens after vector similarity search) by using the [where](https://github.com/tembo-io/pg_vectorize/blob/9e013e3c9c5702c982ca74415ff396074a744cb7/extension/src/api.rs#L54) parameter, but we dont have any docs for this.

1. Add usage of this parameter to documentation including some examples, and
2. Provide some documentation on adding [partial indices ](https://github.com/pgvector/pgvector/issues/259)to a table (which will help improve filtering).

### PR DESCRIPTION
**Pull request by mobley-trent**
Closes #143 
/claim #143

### CODE REVIEW

**Comment by mobley-trent** [comment]
@ChuckHend kindly review

**Comment by ChuckHend** [comment]
I think there is some duplicate work here, the PR before this is addressing the same issue.
https://github.com/tembo-io/pg_vectorize/pull/159

**Comment by mobley-trent** [comment]
> I think there is some duplicate work here, the PR before this is addressing the same issue.
> https://github.com/tembo-io/pg_vectorize/pull/159

These were the changes I initially meant to make since the PR was created moments before mine. Should I proceed with the PR ?

**Comment by ChuckHend** [comment]
@mobley-trent , any improvements to the docs are certainly welcome but this particular bounty is now closed, sorry.

**Pull request closed without merging**
