### PR TITLE
Added chunking support to vectorize.table()

### PR DESCRIPTION
**Pull request by harshtech123**
/claim #142
Added chunk_text function to split into smaller chunks and  You can adjust max_length in chunk_table to your desired text chunk length. Here, I’ve set it to 500 characters.

### CODE REVIEW

**Comment by ChuckHend** [comment]
@harshtech123 - what will the table structure look like in Postgres given chunking during the embedding transformation call as it is proposed in this PR?

**Comment by harshtech123** [comment]
@ChuckHend - 
After chunking, each document will be split into multiple chunks, and each chunk will be assigned its own row in the table.
table structure might looks like 
Screenshot (4)

**Comment by ChuckHend** [comment]
Thank you! Please add a test with an assertion that the table gets set up correctly.

**Comment by harshtech123** [comment]
@ChuckHend kindly review the updates i have made also added some more funtionality to transform.py to handle empty inputs plus added tests with an assertion that the table gets set up correctly.
Screenshot (5)

**Comment by ChuckHend** [comment]
@harshtech123 I think this PR is a bit off the intention behind #142. The changes in this PR are made to `vector-serve`, which is a python service that runs outside of Postgres. We are looking to add the capability to `vectorize.table()`, which is a function call in the Postgres extension and it is defined [here](https://github.com/tembo-io/pg_vectorize/blob/97b2419b4de2136b014c076f91076059135936a1/extension/src/api.rs#L15).

**Comment by harshtech123** [comment]
@ChuckHend  thanks for this confirmation , i am working to add this functionality and i have a question about sql files in extension did i have to update them all as well if i embed this function.

**Comment by ChuckHend** [comment]
There will likely need to be changes made to the code [here](https://github.com/tembo-io/pg_vectorize/blob/97b2419b4de2136b014c076f91076059135936a1/extension/src/api.rs#L15). This feature perhaps needs further scoping.

**Comment by harshtech123** [comment]
@ChuckHend i am closing this pr because i am working on #166

**Pull request closed without merging**
