### PR TITLE
Remove outdated parameters from vectorize.table()

### LINKED ISSUE #146: drop deprecated parameters from `vectorize.table()`
`search_alg` is deprecated, in favor of [index_dist_type](https://github.com/tembo-io/pg_vectorize/blob/9e013e3c9c5702c982ca74415ff396074a744cb7/extension/src/api.rs#L22). Drop search_alg from the parameter and downstream call tree.

### PR DESCRIPTION
**Pull request by zyronite**
What does this PR do?

This PR adds support for chunking text in input columns for the `vectorize.table` function, enhancing document subset retrieval.

/fixes #146 
/claim #146

### CODE REVIEW

**Comment by zyronite** [comment]
@jasonmp85 & @ChuckHend - Guys another one give this a merge too!
Hope this'll fix the Issue as asked, If any changes needed further - Lemme know?!

**Comment by Neptune650** [comment]
@zyronite Hey, I don't understand what exactly this PR does different... The linting fails though, I made my PR because the previous one wouldn't build, but how is this one different.

**Comment by Neptune650** [comment]
Also it seems like you're just doing plagiarism, https://github.com/tembo-io/pg_vectorize/pull/175#issuecomment-2441407515 this one too is just an old commit of my PR.

**Comment by ChuckHend** [comment]
as far as I can tell, https://github.com/tembo-io/pg_vectorize/pull/158 was the first PR to address https://github.com/tembo-io/pg_vectorize/issues/146,  so we will be working with that one first.

**Comment by Neptune650** [comment]
> as far as I can tell, https://github.com/tembo-io/pg_vectorize/pull/158 was the first PR to address https://github.com/tembo-io/pg_vectorize/issues/146,  so we will be working with that one first.

@ChuckHend Correct, then I sent #171 because #158 wasn't building.

**Comment by Neptune650** [comment]
> Hey @Neptune650 , https://github.com/tembo-io/pg_vectorize/pull/158 merged earlier so we closed out this issue and the bounty. Let me know if you have additional scope, otherwise I think we can close this PR.

@ChuckHend Hello, this isn't my PR - I closed mine earlier.

**Pull request closed without merging**
